import 'package:fluent_ui/fluent_ui.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../constants/app_languages.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static List<Locale> get supportedLocales =>
      kSupportedLanguages.map((lang) => Locale(lang.code)).toList();

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'navDashboard': 'Dashboard',
      'navUpdater': 'Updater',
      'navCleaner': 'Cleaner',
      'navOther': 'Other',
      'navLogs': 'Logs / Activity',
      'navSettings': 'Settings',
      'navAbout': 'About',
      'pageDashboardTitle': 'Dashboard',
      'pageUpdaterTitle': 'Updater',
      'pageCleanerTitle': 'Cleaner',
      'pageOtherTitle': 'Other',
      'pageLogsTitle': 'Logs / Activity',
      'pageSettingsTitle': 'Settings',
      'pageAboutTitle': 'About',
      'settingsAppearanceTitle': 'Appearance',
      'settingsLanguage': 'Language',
      'settingsToolVisibilityTitle': 'Tool visibility & safety',
      'settingsShowHighRisk': 'Show high-risk tools',
      'settingsRequireAdmin': 'Always require confirmation before admin actions',
      'settingsLogsTitle': 'Logs and scripts',
      'settingsLogRetention': 'Log retention (days)',
      'settingsOpenTools': 'Open tools folder',
      'settingsOpenBackups': 'Open backups folder',
      'settingsOpenLogs': 'Open logs folder',
      'settingsAppDataRoot': 'App data root',
      'adminBannerTitle': 'Administrator privileges recommended',
      'adminBannerMessage': 'Most updater tools need elevation. Restart the app as Administrator before running them.',
      'adminBannerAction': 'Restart as Administrator',
      'adminBannerDismissedTitle': 'Launch cancelled',
      'adminBannerDismissedMessage': 'UAC prompt was dismissed. The current session stays non-admin.',
      'adminCheckFailedTitle': 'Admin check failed',
      'retry': 'Retry',
      'aboutCredits': 'Credits',
      'aboutCreditIan': 'github: Ian7672 – original Gaming Services blocking script.',
      'aboutCreditIan7672': 'Ian7672 – app integration & packaging.',
      'aboutDescription': 'Ian7672 Windows Toolkit centralises native maintenance actions for keeping Xbox Gaming Services and Windows update components under your control.',
      'aboutVersion': 'Version',
      'aboutSupportTitle': 'Support the project',
      'aboutSupportDescription': 'If this toolkit helps you, consider buying the creator a coffee.',
      'aboutDonateTrakteer': 'Trakteer',
      'aboutDonateKofi': 'Ko-fi',
      'cleanerAdvancedActions': 'Advanced actions',
      'cleanerAdvancedLocations': 'Advanced action paths',
      'cleanerBrowserCache': 'Browser cache',
      'cleanerBrowserCachePaths': 'Browser cache locations',
      'cleanerCleanSelected': 'Clean selected locations',
      'cleanerComponentCleanup': 'Component store cleanup (WinSxS temp)',
      'cleanerDisableHibernation': 'Disable hibernation (removes hiberfil.sys)',
      'cleanerDisableNonAllowlisted': 'Disable non-allowlisted',
      'cleanerDiskCleanupTitle': 'Disk Cleanup (system files)',
      'cleanerDiskLocations': 'Disk cleanup locations',
      'cleanerDriverPackages': 'Device driver packages',
      'cleanerDryRun': 'Dry-run scan',
      'cleanerEnableHibernation': 'Re-enable hibernation (powercfg -h on)',
      'cleanerEnablingHibernation': 'Enabling hibernation...',
      'cleanerEntryError': 'Error',
      'cleanerEntryFiles': 'Files',
      'cleanerEstimatedCleanup': 'Estimated selected cleanup',
      'cleanerIncludeRecycle': 'Include Recycle Bin (requires confirmation)',
      'cleanerJunkHighlight': 'Junk Cleaner',
      'cleanerJunkTitle': 'Junk / Cache Cleaner',
      'cleanerNoBrowsers': 'No browsers detected',
      'cleanerNoStartupItems': 'No startup items detected.',
      'cleanerPerformanceHighlight': 'Performance Cleaner',
      'cleanerPerformanceSubtitle': 'Disable every startup item except the trusted allowlist. Backup is created before modifications.',
      'cleanerPerformanceTitle': 'Performance Cleaner (Startup Manager)',
      'cleanerPreviousWindows': 'Previous Windows installation (windows.old)',
      'cleanerPreviousWindowsNote': 'Note: removing windows.old prevents rolling back to the previous Windows version.',
      'cleanerRefreshBrowsersHint': 'Use the refresh icon above after installing browsers.',
      'cleanerRefreshList': 'Refresh list',
      'cleanerRestoreBackup': 'Restore from backup',
      'cleanerRunScanHint': 'Run a dry-run scan to see estimations.',
      'cleanerScanBrowsers': 'Scan installed browsers',
      'cleanerScanToEstimate': ' (scan to estimate)',
      'cleanerScanning': 'Scanning',
      'cleanerStatusEnabled': 'ENABLED',
      'cleanerStatusDisabled': 'DISABLED',
      'cleanerTemporaryInstall': 'Temporary installation files',
      'cleanerTotalFiles': 'Total files',
      'cleanerTotalSize': 'Total size',
      'cleanerWindowsUpdateCleanup': 'Windows Update Cleanup',
      'dashboardAboutDesc': 'Version info and credit: github.com/Ian7672.',
      'dashboardBackupsHighlight': 'Backups',
      'dashboardCleanerDesc': 'Startup optimizer and junk/cache cleanup suite.',
      'dashboardHighRiskHighlight': 'High-risk toggle',
      'dashboardHistoryHighlight': 'History',
      'dashboardLogsDesc': 'See previous runs, backups, and retention status.',
      'dashboardOtherDesc': 'Sandbox for future tooling experiments.',
      'dashboardReleaseHighlight': 'Release info',
      'dashboardSettingsDesc': 'Preferences, confirmations, theme, and script import.',
      'dashboardThemeHighlight': 'Dark/Light mode',
      'dashboardUpdaterDesc': 'Native Windows/Xbox services, firewall, and policy toggles.',
      'otherPlaceholder': 'Reserved for future diagnostics and utilities.\nAdd entries to tools_manifest.json to surface them here.',
      'generalApplied': 'Applied',
      'generalBlock': 'BLOCK',
      'generalCancel': 'Cancel',
      'generalCopyLog': 'Copy log',
      'generalCreate': 'Create',
      'generalDelete': 'DELETE',
      'generalDeleteValue': 'Delete value',
      'generalDescriptionOptional': 'Description (optional)',
      'generalDisable': 'Disable',
      'generalEnable': 'Enable',
      'generalErrorCode': 'Error code',
      'generalLastBackup': 'Last backup',
      'generalPending': 'Pending',
      'generalPreview': 'Preview',
      'generalProgram': 'PROGRAM',
      'generalRecheckAdmin': 'Re-check admin',
      'generalSet': 'SET',
      'generalSetValue': 'Set {VALUE}',
      'generalStart': 'START',
      'generalStatus': 'Status',
      'generalStop': 'STOP',
      'generalTitle': 'Title',
      'logsActions': 'Actions',
      'logsBackup': 'Backup',
      'logsCleanupTitle': 'Cleanup',
      'logsClearAll': 'Clear all entries',
      'logsClearedMessage': 'All log entries removed.',
      'logsDeleting': 'Deleting...',
      'logsEmpty': 'No recorded runs yet.',
      'toolRiskLevel': 'Risk level',
      'updaterAddCustom': 'Add custom block',
      'updaterAdminOnly': 'ADMIN ONLY',
      'updaterAppsLoadFailed': 'Failed to scan installed apps',
      'updaterCheckingAdmin': 'Checking admin privileges...',
      'updaterCheckingState': 'CHECKING STATE...',
      'updaterCurrentDisabled': 'CURRENT: DISABLED',
      'updaterCurrentEnabled': 'CURRENT: ENABLED',
      'updaterCurrentStateDisabled': 'Current state: Disabled',
      'updaterCurrentStateEnabled': 'Current state: Enabled',
      'updaterCustomDialogTitle': 'Add custom updater block',
      'updaterCustomBlockDefault': 'Custom firewall block created from Updater.',
      'updaterElevationRequired': 'Elevation required',
      'updaterFirewallRules': 'Firewall rules',
      'updaterInstalledAppsTab': 'Installed apps',
      'updaterLoadFailed': 'Failed to load tools',
      'updaterLogPlaceholder': 'Preview, run, or restore to view logs here.',
      'updaterToggleExplanation': '{DISABLE} applies the selected blocks (services, firewall, registry). {ENABLE} restores backups to allow updates again.',
      'updaterNoActions': 'No configured actions for this tool.',
      'updaterNoAppsFound': 'No installed apps with updater executables found.',
      'updaterNoServiceChange': 'No service control change',
      'updaterNoServicesFound': 'No update-related services detected. You can still add rules manually later.',
      'updaterNoTools': 'No tools available. Configure assets/tools_manifest.json.',
      'updaterRegistryChanges': 'Registry changes',
      'updaterReload': 'Reload manifest',
      'updaterRequiresAdmin': 'Requires Administrator',
      'updaterRestartAsAdmin': 'Restart app as Administrator to run this tool.',
      'updaterRiskLabel': 'RISK: {LEVEL}',
      'updaterProgramRule': 'Program {VALUE}',
      'updaterServiceRule': 'Service {VALUE}',
      'updaterServiceChanges': 'Service changes',
      'updaterServicesLoadFailed': 'Failed to enumerate services',
      'updaterServicesTab': 'Services',
      'updaterStandardPerms': 'Standard privileges',
      'updaterStateCheckFailed': 'State check failed',
      'updaterStateNotConfigured': 'STATE: NOT CONFIGURED',
      'updaterStateUnavailable': 'Current state unavailable until actions are configured.',
      'updaterStateUnknown': 'STATE UNKNOWN',
      'updaterTargetDisable': 'TARGET: DISABLE',
      'updaterTitlePlaceholder': 'e.g., Block Foo Updater',
      'updaterToolNotConfigured': 'Tool not configured',
      'updaterToolNotConfiguredHint': 'Add serviceActions, registryActions, or firewallActions in tools_manifest.json.'
    },
    'id': {
      'navDashboard': 'Dasbor',
      'navUpdater': 'Pembaruan',
      'navCleaner': 'Pembersih',
      'navOther': 'Lainnya',
      'navLogs': 'Log / Aktivitas',
      'navSettings': 'Pengaturan',
      'navAbout': 'Tentang',
      'pageDashboardTitle': 'Dasbor',
      'pageUpdaterTitle': 'Updater',
      'pageCleanerTitle': 'Pembersih',
      'pageOtherTitle': 'Lainnya',
      'pageLogsTitle': 'Log / Aktivitas',
      'pageSettingsTitle': 'Pengaturan',
      'pageAboutTitle': 'Tentang',
      'settingsAppearanceTitle': 'Tampilan',
      'settingsLanguage': 'Bahasa',
      'settingsToolVisibilityTitle': 'Visibilitas & keamanan alat',
      'settingsShowHighRisk': 'Tampilkan alat berisiko tinggi',
      'settingsRequireAdmin': 'Selalu minta konfirmasi sebelum tindakan admin',
      'settingsLogsTitle': 'Log dan skrip',
      'settingsLogRetention': 'Retensi log (hari)',
      'settingsOpenTools': 'Buka folder tools',
      'settingsOpenBackups': 'Buka folder cadangan',
      'settingsOpenLogs': 'Buka folder log',
      'settingsAppDataRoot': 'Folder data aplikasi',
      'adminBannerTitle': 'Privileg Admin disarankan',
      'adminBannerMessage': 'Sebagian besar alat updater perlu akses administrator. Jalankan ulang aplikasi sebagai Admin sebelum menjalankannya.',
      'adminBannerAction': 'Mulai ulang sebagai Admin',
      'adminBannerDismissedTitle': 'Peluncuran dibatalkan',
      'adminBannerDismissedMessage': 'Prompt UAC ditutup. Sesi ini tetap non-admin.',
      'adminCheckFailedTitle': 'Pemeriksaan admin gagal',
      'retry': 'Coba lagi',
      'aboutCredits': 'Kredit',
      'aboutCreditIan': 'github: Ian7672 – skrip pemblokiran Gaming Services asli.',
      'aboutCreditIan7672': 'Ian7672 – integrasi aplikasi & paket.',
      'aboutDescription': 'Ian7672 Windows Toolkit menggabungkan tindakan perawatan native untuk menjaga Xbox Gaming Services dan komponen Windows Update tetap dalam kendali Anda.',
      'aboutVersion': 'Versi',
      'aboutSupportTitle': 'Dukung proyek',
      'aboutSupportDescription': 'Kalau toolkit ini membantu, bisa traktir pembuatnya kopi.',
      'aboutDonateTrakteer': 'Trakteer',
      'aboutDonateKofi': 'Ko-fi',
      'cleanerAdvancedActions': 'Tindakan lanjutan',
      'cleanerAdvancedLocations': 'Lokasi tindakan lanjutan',
      'cleanerBrowserCache': 'Cache peramban',
      'cleanerBrowserCachePaths': 'Lokasi cache peramban',
      'cleanerCleanSelected': 'Bersihkan lokasi terpilih',
      'cleanerComponentCleanup': 'Pembersihan komponen (WinSxS sementara)',
      'cleanerDisableHibernation': 'Nonaktifkan hibernasi (hapus hiberfil.sys)',
      'cleanerDisableNonAllowlisted': 'Nonaktifkan yang tidak ada dalam daftar aman',
      'cleanerDiskCleanupTitle': 'Pembersihan Disk (file sistem)',
      'cleanerDiskLocations': 'Lokasi pembersihan disk',
      'cleanerDriverPackages': 'Paket driver',
      'cleanerDryRun': 'Pindai simulasi',
      'cleanerEnableHibernation': 'Aktifkan lagi hibernasi (powercfg -h on)',
      'cleanerEnablingHibernation': 'Mengaktifkan hibernasi...',
      'cleanerEntryError': 'Kesalahan',
      'cleanerEntryFiles': 'Berkas',
      'cleanerEstimatedCleanup': 'Perkiraan pembersihan terpilih',
      'cleanerIncludeRecycle': 'Sertakan Recycle Bin (perlu konfirmasi)',
      'cleanerJunkHighlight': 'Pembersih Sampah',
      'cleanerJunkTitle': 'Pembersih Sampah / Cache',
      'cleanerNoBrowsers': 'Tidak ada peramban terdeteksi',
      'cleanerNoStartupItems': 'Tidak ada item startup yang ditemukan.',
      'cleanerPerformanceHighlight': 'Pembersih Kinerja',
      'cleanerPerformanceSubtitle': 'Nonaktifkan semua item startup selain daftar aman. Cadangan dibuat sebelum perubahan.',
      'cleanerPerformanceTitle': 'Pembersih Kinerja (Pengelola Startup)',
      'cleanerPreviousWindows': 'Instalasi Windows sebelumnya (windows.old)',
      'cleanerPreviousWindowsNote': 'Catatan: menghapus windows.old membuat Anda tidak bisa rollback ke versi Windows sebelumnya.',
      'cleanerRefreshBrowsersHint': 'Gunakan ikon refresh di atas setelah memasang peramban.',
      'cleanerRefreshList': 'Muat ulang daftar',
      'cleanerRestoreBackup': 'Pulihkan dari cadangan',
      'cleanerRunScanHint': 'Jalankan pemindaian simulasi untuk melihat perkiraan.',
      'cleanerScanBrowsers': 'Pindai peramban terpasang',
      'cleanerScanToEstimate': ' (pindai untuk perkiraan)',
      'cleanerScanning': 'Memindai',
      'cleanerStatusEnabled': 'Diaktifkan',
      'cleanerStatusDisabled': 'Dinonaktifkan',
      'cleanerTemporaryInstall': 'Berkas instalasi sementara',
      'cleanerTotalFiles': 'Total berkas',
      'cleanerTotalSize': 'Total ukuran',
      'cleanerWindowsUpdateCleanup': 'Pembersihan Windows Update',
      'dashboardAboutDesc': 'Info versi dan kredit: github.com/Ian7672.',
      'dashboardBackupsHighlight': 'Cadangan',
      'dashboardCleanerDesc': 'Pengoptimal startup dan rangkaian pembersih sampah/cache.',
      'dashboardHighRiskHighlight': 'Toggle risiko tinggi',
      'dashboardHistoryHighlight': 'Riwayat',
      'dashboardLogsDesc': 'Lihat riwayat eksekusi, cadangan, dan status retensi.',
      'dashboardOtherDesc': 'Sandbox untuk eksperimen alat berikutnya.',
      'dashboardReleaseHighlight': 'Info rilis',
      'dashboardSettingsDesc': 'Preferensi, konfirmasi, tema, dan impor skrip.',
      'dashboardThemeHighlight': 'Mode gelap/terang',
      'dashboardUpdaterDesc': 'Layanan Windows/Xbox native, firewall, dan pengaturan kebijakan.',
      'generalApplied': 'Diterapkan',
      'generalBlock': 'BLOKIR',
      'generalCancel': 'Batal',
      'generalCopyLog': 'Salin log',
      'generalCreate': 'Buat',
      'generalDelete': 'HAPUS',
      'generalDeleteValue': 'Hapus nilai',
      'generalDescriptionOptional': 'Deskripsi (opsional)',
      'generalDisable': 'Nonaktifkan',
      'generalEnable': 'Aktifkan',
      'generalErrorCode': 'Kode kesalahan',
      'generalLastBackup': 'Cadangan terakhir',
      'generalPending': 'Menunggu',
      'generalPreview': 'Pratinjau',
      'generalProgram': 'PROGRAM',
      'generalRecheckAdmin': 'Periksa admin lagi',
      'generalSet': 'SETEL',
      'generalSetValue': 'Setel {VALUE}',
      'generalStart': 'MULAI',
      'generalStatus': 'Status',
      'generalStop': 'HENTIKAN',
      'generalTitle': 'Judul',
      'logsActions': 'Aksi',
      'logsBackup': 'Cadangan',
      'logsCleanupTitle': 'Pembersihan',
      'logsClearAll': 'Hapus semua entri',
      'logsClearedMessage': 'Semua entri log telah dihapus.',
      'logsDeleting': 'Menghapus...',
      'logsEmpty': 'Belum ada catatan eksekusi.',
      'toolRiskLevel': 'Tingkat risiko',
      'updaterAddCustom': 'Tambah blokir kustom',
      'updaterAdminOnly': 'KHUSUS ADMIN',
      'updaterAppsLoadFailed': 'Gagal memindai aplikasi terinstal',
      'updaterCheckingAdmin': 'Memeriksa hak admin...',
      'updaterCheckingState': 'MEMERIKSA STATUS...',
      'updaterCurrentDisabled': 'SAAT INI: DINONAKTIFKAN',
      'updaterCurrentEnabled': 'SAAT INI: DIAKTIFKAN',
      'updaterCurrentStateDisabled': 'Status saat ini: Dinonaktifkan',
      'updaterCurrentStateEnabled': 'Status saat ini: Diaktifkan',
      'updaterCustomDialogTitle': 'Tambah blokir updater kustom',
      'updaterCustomBlockDefault': 'Blokir firewall kustom dibuat dari Updater.',
      'updaterElevationRequired': 'Butuh hak admin',
      'updaterFirewallRules': 'Aturan firewall',
      'updaterInstalledAppsTab': 'Aplikasi terpasang',
      'updaterLoadFailed': 'Gagal memuat alat',
      'updaterLogPlaceholder': 'Pratinjau, jalankan, atau pulihkan untuk melihat log di sini.',
      'updaterToggleExplanation': '{DISABLE} akan menerapkan blokir (layanan, firewall, registry). {ENABLE} memulihkan perubahan agar updater dapat berjalan lagi.',
      'updaterNoActions': 'Tidak ada tindakan terkonfigurasi untuk alat ini.',
      'updaterNoAppsFound': 'Tidak ada aplikasi dengan executable updater.',
      'updaterNoServiceChange': 'Tidak ada perubahan layanan',
      'updaterNoServicesFound': 'Tidak ada layanan terkait update ditemukan. Anda tetap bisa menambah aturan manual.',
      'updaterNoTools': 'Tidak ada alat tersedia. Konfigurasikan assets/tools_manifest.json.',
      'updaterRegistryChanges': 'Perubahan registry',
      'updaterReload': 'Muat ulang manifest',
      'updaterRequiresAdmin': 'Memerlukan Administrator',
      'updaterRestartAsAdmin': 'Jalankan ulang aplikasi sebagai Administrator sebelum menjalankan alat ini.',
      'updaterRiskLabel': 'RISIKO: {LEVEL}',
      'updaterProgramRule': 'Program {VALUE}',
      'updaterServiceRule': 'Layanan {VALUE}',
      'updaterServiceChanges': 'Perubahan layanan',
      'updaterServicesLoadFailed': 'Gagal membaca layanan',
      'updaterServicesTab': 'Layanan',
      'updaterStandardPerms': 'Hak standar',
      'updaterStateCheckFailed': 'Pemeriksaan status gagal',
      'updaterStateNotConfigured': 'STATUS: BELUM DIKONFIGURASI',
      'updaterStateUnavailable': 'Status saat ini belum tersedia sampai tindakan dikonfigurasikan.',
      'updaterStateUnknown': 'STATUS TIDAK DIKETAHUI',
      'updaterTargetDisable': 'TARGET: NONAKTIFKAN',
      'updaterTitlePlaceholder': 'mis. Blokir Foo Updater',
      'updaterToolNotConfigured': 'Alat belum dikonfigurasi',
      'updaterToolNotConfiguredHint': 'Tambahkan serviceActions, registryActions, atau firewallActions di tools_manifest.json.'
    },
    'zh': {
      'navDashboard': '仪表板',
      'navUpdater': '更新ツール',
      'navCleaner': '清理器',
      'navOther': '其他',
      'navLogs': '日志 / 活动',
      'navSettings': '设置',
      'navAbout': '关于',
      'pageDashboardTitle': '仪表板',
      'pageUpdaterTitle': '更新器',
      'pageCleanerTitle': '清理器',
      'pageOtherTitle': '其他',
      'pageLogsTitle': '日志 / 活动',
      'pageSettingsTitle': '设置',
      'pageAboutTitle': '关于',
      'dashboardAboutDesc': '版本信息和致谢：github.com/Ian7672。',
      'dashboardBackupsHighlight': '备份',
      'dashboardCleanerDesc': '启动优化和垃圾/缓存清理工具套件。',
      'dashboardHighRiskHighlight': '高风险开关',
      'dashboardHistoryHighlight': '历史记录',
      'dashboardLogsDesc': '查看之前的运行记录、备份和保留状态。',
      'dashboardOtherDesc': '用于未来工具实验的沙盒。',
      'dashboardReleaseHighlight': '发布信息',
      'dashboardSettingsDesc': '首选项、确认、主题和脚本导入。',
      'dashboardThemeHighlight': '深色/浅色模式',
      'dashboardUpdaterDesc': '原生 Windows/Xbox 服务、防火墙和策略切换。',
      'settingsAppearanceTitle': '外观',
      'settingsLanguage': '语言',
      'settingsToolVisibilityTitle': '工具可见性与安全',
      'settingsShowHighRisk': '显示高风险工具',
      'settingsRequireAdmin': '管理员操作前始终确认',
      'settingsLogsTitle': '日志和脚本',
      'settingsLogRetention': '日志保留（天）',
      'settingsOpenTools': '打开工具文件夹',
      'settingsOpenBackups': '打开备份文件夹',
      'settingsOpenLogs': '打开日志文件夹',
      'settingsAppDataRoot': '应用数据根目录',
      'adminBannerTitle': '建议使用管理员权限',
      'adminBannerMessage': '大多数更新工具需要提升权限。运行前请以管理员身份重启应用。',
      'adminBannerAction': '以管理员重新启动',
      'adminBannerDismissedTitle': '启动已取消',
      'adminBannerDismissedMessage': 'UAC 提示被关闭。当前会话仍为非管理员。',
      'adminCheckFailedTitle': '管理员检查失败',
      'retry': '重试',
      'aboutCredits': '致谢',
      'aboutCreditIan': 'github: Ian7672 - 原始 Gaming Services 阻断脚本。',
      'aboutCreditIan7672': 'Ian7672 - 应用集成与打包。',
      'aboutDescription': 'Ian7672 Windows Toolkit 汇集原生维护操作，帮助你掌控 Xbox Gaming Services 和 Windows 更新组件。',
      'aboutVersion': '版本',
      'cleanerAdvancedActions': '高级操作',
      'cleanerAdvancedLocations': '高级操作路径',
      'cleanerBrowserCache': '浏览器缓存',
      'cleanerBrowserCachePaths': '浏览器缓存位置',
      'cleanerCleanSelected': '清理所选位置',
      'cleanerComponentCleanup': '组件存储清理（WinSxS 临时）',
      'cleanerDisableHibernation': '禁用休眠（删除 hiberfil.sys）',
      'cleanerDisableNonAllowlisted': '禁用未在允许列表中的项目',
      'cleanerDiskCleanupTitle': '磁盘清理（系统文件）',
      'cleanerDiskLocations': '磁盘清理位置',
      'cleanerDriverPackages': '设备驱动程序包',
      'cleanerDryRun': '模拟扫描',
      'cleanerEnableHibernation': '重新启用休眠（powercfg -h on）',
      'cleanerEnablingHibernation': '正在启用休眠...',
      'cleanerEntryError': '错误',
      'cleanerEntryFiles': '文件',
      'cleanerEstimatedCleanup': '预计可清理',
      'cleanerIncludeRecycle': '包含回收站（需要确认）',
      'cleanerJunkHighlight': '垃圾清理',
      'cleanerJunkTitle': '垃圾/缓存清理',
      'cleanerNoBrowsers': '未检测到浏览器',
      'cleanerNoStartupItems': '未发现启动项。',
      'cleanerPerformanceHighlight': '性能清理',
      'cleanerPerformanceSubtitle': '禁用除受信任白名单外的所有启动项。更改前会创建备份。',
      'cleanerPerformanceTitle': '性能清理（启动项管理器）',
      'cleanerPreviousWindows': '先前的 Windows 安装（windows.old）',
      'cleanerPreviousWindowsNote': '注意：删除 windows.old 会阻止回滚到之前的 Windows 版本。',
      'cleanerRefreshBrowsersHint': '安装浏览器后，请使用上方的刷新按钮。',
      'cleanerRefreshList': '刷新列表',
      'cleanerRestoreBackup': '从备份恢复',
      'cleanerRunScanHint': '运行模拟扫描以查看估算。',
      'cleanerScanBrowsers': '扫描已安装的浏览器',
      'cleanerScanToEstimate': ' （扫描以估算）',
      'cleanerScanning': '正在扫描',
      'cleanerStatusEnabled': '已启用',
      'cleanerStatusDisabled': '已禁用',
      'cleanerTemporaryInstall': '临时安装文件',
      'cleanerTotalFiles': '文件总数',
      'cleanerTotalSize': '总大小',
      'cleanerWindowsUpdateCleanup': 'Windows 更新清理',
      'generalApplied': '已应用',
      'generalBlock': '阻止',
      'generalCancel': '取消',
      'generalCopyLog': '复制日志',
      'generalCreate': '创建',
      'generalDelete': '删除',
      'generalDeleteValue': '删除值',
      'generalDescriptionOptional': '描述（可选）',
      'generalDisable': '禁用',
      'generalEnable': '启用',
      'generalErrorCode': '错误代码',
      'generalLastBackup': '上次备份',
      'generalPending': '待处理',
      'generalPreview': '预览',
      'generalProgram': '程序',
      'generalRecheckAdmin': '重新检查管理员权限',
      'generalSet': '设置',
      'generalSetValue': '设置 {VALUE}',
      'generalStart': '启动',
      'generalStatus': '状态',
      'generalStop': '停止',
      'generalTitle': '标题',
      'logsActions': '操作',
      'logsBackup': '备份',
      'logsCleanupTitle': '清理',
      'logsClearAll': '清除所有条目',
      'logsClearedMessage': '所有日志条目已删除。',
      'logsDeleting': '正在删除...',
      'logsEmpty': '尚无执行记录。',
      'otherPlaceholder': '预留给未来的诊断和工具。\\n在 tools_manifest.json 中添加条目即可在此显示。',
      'toolRiskLevel': '风险等级',
      'updaterAddCustom': '添加自定义阻止项',
      'updaterAdminOnly': '仅限管理员',
      'updaterAppsLoadFailed': '扫描已安装应用失败',
      'updaterCheckingAdmin': '正在检查管理员权限...',
      'updaterCheckingState': '正在检查状态...',
      'updaterCurrentDisabled': '当前：已禁用',
      'updaterCurrentEnabled': '当前：已启用',
      'updaterCurrentStateDisabled': '当前状态：已禁用',
      'updaterCurrentStateEnabled': '当前状态：已启用',
      'updaterCustomBlockDefault': '从 Updater 创建的自定义防火墙阻止项。',
      'updaterCustomDialogTitle': '添加自定义更新阻止项',
      'updaterElevationRequired': '需要提升权限',
      'updaterFirewallRules': '防火墙规则',
      'updaterInstalledAppsTab': '已安装的应用',
      'updaterLoadFailed': '加载工具失败',
      'updaterLogPlaceholder': '在此预览、运行或恢复以查看日志。',
      'updaterToggleExplanation': '{DISABLE} 会应用所选阻止项（服务、防火墙、注册表）来关闭更新器，{ENABLE} 会恢复备份，让更新器再次运行。',
      'updaterNoActions': '此工具没有配置的操作。',
      'updaterNoAppsFound': '未找到带更新程序的已安装应用。',
      'updaterNoServiceChange': '没有服务控制更改',
      'updaterNoServicesFound': '未检测到与更新相关的服务。你仍可稍后手动添加规则。',
      'updaterNoTools': '没有可用工具。请配置 assets/tools_manifest.json。',
      'updaterProgramRule': '程序 {VALUE}',
      'updaterRegistryChanges': '注册表更改',
      'updaterReload': '重新加载 manifest',
      'updaterRequiresAdmin': '需要管理员',
      'updaterRestartAsAdmin': '以管理员身份重新启动应用以运行此工具。',
      'updaterRiskLabel': '风险：{LEVEL}',
      'updaterServiceChanges': '服务更改',
      'updaterServiceRule': '服务 {VALUE}',
      'updaterServicesLoadFailed': '枚举服务失败',
      'updaterServicesTab': '服务',
      'updaterStandardPerms': '标准权限',
      'updaterStateCheckFailed': '状态检查失败',
      'updaterStateNotConfigured': '状态：未配置',
      'updaterStateUnavailable': '在配置操作之前，无法获得当前状态。',
      'updaterStateUnknown': '状态未知',
      'updaterTargetDisable': '目标：禁用',
      'updaterTitlePlaceholder': '例如：阻止 Foo Updater',
      'updaterToolNotConfigured': '工具未配置',
      'updaterToolNotConfiguredHint': '请在 tools_manifest.json 中添加 serviceActions、registryActions 或 firewallActions。'
    },
    'ja': {
      'navDashboard': 'ダッシュボード',
      'navUpdater': 'アップデーター',
      'navCleaner': 'クリーナー',
      'navOther': 'その他',
      'navLogs': 'ログ / アクティビティ',
      'navSettings': '設定',
      'navAbout': '情報',
      'pageDashboardTitle': 'ダッシュボード',
      'pageUpdaterTitle': 'アップデーター',
      'pageCleanerTitle': 'クリーナー',
      'pageOtherTitle': 'その他',
      'pageLogsTitle': 'ログ / アクティビティ',
      'pageSettingsTitle': '設定',
      'pageAboutTitle': '情報',
      'dashboardAboutDesc': 'バージョン情報とクレジット: github.com/Ian7672。',
      'dashboardBackupsHighlight': 'バックアップ',
      'dashboardCleanerDesc': '起動最適化とジャンク/キャッシュ クリーンアップスイート。',
      'dashboardHighRiskHighlight': 'ハイリスク切り替え',
      'dashboardHistoryHighlight': '履歴',
      'dashboardLogsDesc': '過去の実行、バックアップ、保持状況を確認します。',
      'dashboardOtherDesc': '将来のツール実験用サンドボックス。',
      'dashboardReleaseHighlight': 'リリース情報',
      'dashboardSettingsDesc': '設定、確認、テーマ、スクリプトのインポート。',
      'dashboardThemeHighlight': 'ダーク/ライトモード',
      'dashboardUpdaterDesc': 'ネイティブの Windows/Xbox サービス、ファイアウォール、ポリシー切り替え。',
      'settingsAppearanceTitle': '外観',
      'settingsLanguage': '言語',
      'settingsToolVisibilityTitle': 'ツール表示と安全性',
      'settingsShowHighRisk': '高リスクツールを表示',
      'settingsRequireAdmin': '管理者操作前に必ず確認',
      'settingsLogsTitle': 'ログとスクリプト',
      'settingsLogRetention': 'ログ保持（日数）',
      'settingsOpenTools': 'ツールフォルダーを開く',
      'settingsOpenBackups': 'バックアップフォルダーを開く',
      'settingsOpenLogs': 'ログフォルダーを開く',
      'settingsAppDataRoot': 'アプリデータルート',
      'adminBannerTitle': '管理者権限を推奨',
      'adminBannerMessage':
          'ほとんどのアップデーターには昇格が必要です。実行前に管理者として再起動してください。',
      'adminBannerAction': '管理者として再起動',
      'adminBannerDismissedTitle': '起動がキャンセルされました',
      'adminBannerDismissedMessage': 'UAC が閉じられました。現在のセッションは非管理者のままです。',
      'adminCheckFailedTitle': '管理者チェックに失敗',
      'retry': '再試行',
    },
    'ko': {
      'navDashboard': '대시보드',
      'navUpdater': '업데이트 도구',
      'navCleaner': '클리너',
      'navOther': '기타',
      'navLogs': '로그 / 활동',
      'navSettings': '설정',
      'navAbout': '정보',
      'pageDashboardTitle': '대시보드',
      'pageUpdaterTitle': '업데이터',
      'pageCleanerTitle': '클리너',
      'pageOtherTitle': '기타',
      'pageLogsTitle': '로그 / 활동',
      'pageSettingsTitle': '설정',
      'pageAboutTitle': '정보',
      'dashboardAboutDesc': '버전 정보 및 크레딧: github.com/Ian7672.',
      'dashboardBackupsHighlight': '백업',
      'dashboardCleanerDesc': '시작 최적화 및 정크/캐시 정리 도구 모음.',
      'dashboardHighRiskHighlight': '고위험 토글',
      'dashboardHistoryHighlight': '기록',
      'dashboardLogsDesc': '이전 실행, 백업, 보존 상태를 확인합니다.',
      'dashboardOtherDesc': '향후 도구 실험을 위한 샌드박스.',
      'dashboardReleaseHighlight': '릴리스 정보',
      'dashboardSettingsDesc': '환경설정, 확인, 테마 및 스크립트 가져오기.',
      'dashboardThemeHighlight': '다크/라이트 모드',
      'dashboardUpdaterDesc': '기본 Windows/Xbox 서비스, 방화벽 및 정책 전환.',
      'settingsAppearanceTitle': '모양',
      'settingsLanguage': '언어',
      'settingsToolVisibilityTitle': '도구 표시 및 보안',
      'settingsShowHighRisk': '고위험 도구 표시',
      'settingsRequireAdmin': '관리자 작업 전 항상 확인',
      'settingsLogsTitle': '로그 및 스크립트',
      'settingsLogRetention': '로그 보관(일수)',
      'settingsOpenTools': '도구 폴더 열기',
      'settingsOpenBackups': '백업 폴더 열기',
      'settingsOpenLogs': '로그 폴더 열기',
      'settingsAppDataRoot': '앱 데이터 루트',
      'adminBannerTitle': '관리자 권한 권장',
      'adminBannerMessage':
          '대부분의 업데이트 도구는 권한 상승이 필요합니다. 실행 전에 관리자 모드로 다시 시작하세요.',
      'adminBannerAction': '관리자로 다시 시작',
      'adminBannerDismissedTitle': '실행이 취소되었습니다',
      'adminBannerDismissedMessage': 'UAC 창이 닫혔습니다. 현재 세션은 비관리자 상태로 유지됩니다.',
      'adminCheckFailedTitle': '관리자 확인 실패',
      'retry': '재시도',
    },
    'ar': {
      'navDashboard': 'لوحة التحكم',
      'navUpdater': 'أداة التحديث',
      'navCleaner': 'أداة التنظيف',
      'navOther': 'أخرى',
      'navLogs': 'السجلات / النشاط',
      'navSettings': 'الإعدادات',
      'navAbout': 'حول',
      'pageDashboardTitle': 'لوحة التحكم',
      'pageUpdaterTitle': 'أداة التحديث',
      'pageCleanerTitle': 'أداة التنظيف',
      'pageOtherTitle': 'أخرى',
      'pageLogsTitle': 'السجلات / النشاط',
      'pageSettingsTitle': 'الإعدادات',
      'pageAboutTitle': 'حول',
      'dashboardAboutDesc': 'معلومات الإصدار والاعتمادات: github.com/Ian7672.',
      'dashboardBackupsHighlight': 'النسخ الاحتياطية',
      'dashboardCleanerDesc': 'حزمة لتحسين بدء التشغيل وتنظيف المهملات/الذاكرة المؤقتة.',
      'dashboardHighRiskHighlight': 'مفتاح التبديل عالي المخاطر',
      'dashboardHistoryHighlight': 'السجل',
      'dashboardLogsDesc': 'اطّلع على التشغيلات السابقة والنسخ الاحتياطية وحالة الاحتفاظ.',
      'dashboardOtherDesc': 'بيئة معزولة لتجربة الأدوات المستقبلية.',
      'dashboardReleaseHighlight': 'معلومات الإصدار',
      'dashboardSettingsDesc': 'التفضيلات والتأكيدات والمظهر واستيراد السكربتات.',
      'dashboardThemeHighlight': 'وضع داكن/فاتح',
      'dashboardUpdaterDesc': 'خدمات Windows/Xbox الأصلية وجدار الحماية ومفاتيح السياسات.',
      'settingsAppearanceTitle': 'المظهر',
      'settingsLanguage': 'اللغة',
      'settingsToolVisibilityTitle': 'ظهور الأدوات والأمان',
      'settingsShowHighRisk': 'إظهار الأدوات عالية المخاطر',
      'settingsRequireAdmin': 'تأكيد قبل تنفيذ إجراءات المسؤول دائمًا',
      'settingsLogsTitle': 'السجلات والبرامج النصية',
      'settingsLogRetention': 'مدة الاحتفاظ بالسجلات (أيام)',
      'settingsOpenTools': 'فتح مجلد الأدوات',
      'settingsOpenBackups': 'فتح مجلد النسخ الاحتياطية',
      'settingsOpenLogs': 'فتح مجلد السجلات',
      'settingsAppDataRoot': 'مسار بيانات التطبيق',
      'adminBannerTitle': 'يفضل تشغيل كمسؤول',
      'adminBannerMessage':
          'معظم أدوات التحديث تحتاج صلاحيات مرتفعة. أعد تشغيل التطبيق كمسؤول قبل استخدامها.',
      'adminBannerAction': 'إعادة التشغيل كمسؤول',
      'adminBannerDismissedTitle': 'تم إلغاء التشغيل',
      'adminBannerDismissedMessage':
          'تم إغلاق مطالبة UAC. ستبقى هذه الجلسة بدون صلاحيات مسؤول.',
      'adminCheckFailedTitle': 'فشل فحص المسؤول',
      'retry': 'إعادة المحاولة',
    },
    'ru': {
      'navDashboard': 'Панель',
      'navUpdater': 'Обновления',
      'navCleaner': 'Очистка',
      'navOther': 'Прочее',
      'navLogs': 'Журналы / Активность',
      'navSettings': 'Настройки',
      'navAbout': 'О программе',
      'pageDashboardTitle': 'Панель',
      'pageUpdaterTitle': 'Обновления',
      'pageCleanerTitle': 'Очистка',
      'pageOtherTitle': 'Прочее',
      'pageLogsTitle': 'Журналы / Активность',
      'pageSettingsTitle': 'Настройки',
      'pageAboutTitle': 'О программе',
      'dashboardAboutDesc': 'Информация о версии и благодарности: github.com/Ian7672.',
      'dashboardBackupsHighlight': 'Резервные копии',
      'dashboardCleanerDesc': 'Набор для оптимизации автозапуска и очистки мусора/кэша.',
      'dashboardHighRiskHighlight': 'Переключатель повышенного риска',
      'dashboardHistoryHighlight': 'История',
      'dashboardLogsDesc': 'Просматривайте прошлые запуски, резервные копии и статус хранения.',
      'dashboardOtherDesc': 'Песочница для будущих экспериментов с инструментами.',
      'dashboardReleaseHighlight': 'Сведения о релизе',
      'dashboardSettingsDesc': 'Предпочтения, подтверждения, тема и импорт скриптов.',
      'dashboardThemeHighlight': 'Темный/светлый режим',
      'dashboardUpdaterDesc': 'Встроенные службы Windows/Xbox, брандмауэр и переключатели политик.',
      'settingsAppearanceTitle': 'Внешний вид',
      'settingsLanguage': 'Язык',
      'settingsToolVisibilityTitle': 'Отображение и безопасность инструментов',
      'settingsShowHighRisk': 'Показывать опасные инструменты',
      'settingsRequireAdmin': 'Всегда запрашивать подтверждение для действий админа',
      'settingsLogsTitle': 'Журналы и скрипты',
      'settingsLogRetention': 'Хранение журналов (дней)',
      'settingsOpenTools': 'Открыть папку инструментов',
      'settingsOpenBackups': 'Открыть папку резервных копий',
      'settingsOpenLogs': 'Открыть папку журналов',
      'settingsAppDataRoot': 'Корень данных приложения',
      'adminBannerTitle': 'Рекомендуется режим администратора',
      'adminBannerMessage':
          'Большинство инструментов обновления требуют повышенных прав. Перезапустите приложение от имени администратора.',
      'adminBannerAction': 'Перезапустить как администратор',
      'adminBannerDismissedTitle': 'Запуск отменён',
      'adminBannerDismissedMessage':
          'Окно UAC закрыто. Текущая сессия останется без прав администратора.',
      'adminCheckFailedTitle': 'Проверка прав администратора не удалась',
      'retry': 'Повторить',
    },
    'hi': {
      'navDashboard': 'डैशबोर्ड',
      'navUpdater': 'अद्यतन उपकरण',
      'navCleaner': 'क्लीनर',
      'navOther': 'अन्य',
      'navLogs': 'लॉग / गतिविधि',
      'navSettings': 'सेटिंग्स',
      'navAbout': 'जानकारी',
      'pageDashboardTitle': 'डैशबोर्ड',
      'pageUpdaterTitle': 'अपडेटर',
      'pageCleanerTitle': 'क्लीनर',
      'pageOtherTitle': 'अन्य',
      'pageLogsTitle': 'लॉग / गतिविधि',
      'pageSettingsTitle': 'सेटिंग्स',
      'pageAboutTitle': 'जानकारी',
      'dashboardAboutDesc': 'संस्करण जानकारी और श्रेय: github.com/Ian7672.',
      'dashboardBackupsHighlight': 'बैकअप',
      'dashboardCleanerDesc': 'स्टार्टअप ऑप्टिमाइज़र और कचरा/कैश सफाई सूट.',
      'dashboardHighRiskHighlight': 'उच्च-जोखिम टॉगल',
      'dashboardHistoryHighlight': 'इतिहास',
      'dashboardLogsDesc': 'पिछले रन, बैकअप और प्रतिधारण स्थिति देखें.',
      'dashboardOtherDesc': 'भविष्य के टूल प्रयोगों के लिए सैंडबॉक्स.',
      'dashboardReleaseHighlight': 'रिलीज़ जानकारी',
      'dashboardSettingsDesc': 'प्राथमिकताएँ, पुष्टिकरण, थीम और स्क्रिप्ट आयात.',
      'dashboardThemeHighlight': 'डार्क/लाइट मोड',
      'dashboardUpdaterDesc': 'स्थानीय Windows/Xbox सेवाएँ, फ़ायरवॉल और नीति टॉगल.',
      'settingsAppearanceTitle': 'रूप-रंग',
      'settingsLanguage': 'भाषा',
      'settingsToolVisibilityTitle': 'टूल दृश्यता व सुरक्षा',
      'settingsShowHighRisk': 'उच्च जोखिम वाले टूल दिखाएँ',
      'settingsRequireAdmin': 'एडमिन कार्य से पहले हमेशा पुष्टि करें',
      'settingsLogsTitle': 'लॉग और स्क्रिप्ट',
      'settingsLogRetention': 'लॉग रखने की अवधि (दिन)',
      'settingsOpenTools': 'टूल्स फ़ोल्डर खोलें',
      'settingsOpenBackups': 'बैकअप फ़ोल्डर खोलें',
      'settingsOpenLogs': 'लॉग फ़ोल्डर खोलें',
      'settingsAppDataRoot': 'ऐप डेटा रूट',
      'adminBannerTitle': 'प्रशासक अधिकार सुझाव',
      'adminBannerMessage':
          'अधिकांश अपडेटर टूल्स को एडमिन अधिकार चाहिए। चलाने से पहले ऐप को एडमिन के रूप में पुनः प्रारंभ करें।',
      'adminBannerAction': 'एडमिन के रूप में पुनः प्रारंभ करें',
      'adminBannerDismissedTitle': 'प्रारंभ रद्द',
      'adminBannerDismissedMessage':
          'UAC प्रॉम्प्ट बंद किया गया। यह सत्र गैर-एडमिन रहेगा।',
      'adminCheckFailedTitle': 'एडमिन जांच विफल',
      'retry': 'पुनः प्रयास',
    },
  };

  String _string(String key) {
    final values = _localizedValues[locale.languageCode] ??
        _localizedValues['en']!;
    return values[key] ?? _localizedValues['en']![key] ?? key;
  }

  String text(String key, String fallback) {
    final values = _localizedValues[locale.languageCode];
    if (values != null && values[key] != null) {
      return values[key]!;
    }
    final english = _localizedValues['en'];
    if (english != null && english[key] != null) {
      return english[key]!;
    }
    return fallback;
  }

  String get navDashboard => _string('navDashboard');
  String get navUpdater => _string('navUpdater');
  String get navCleaner => _string('navCleaner');
  String get navOther => _string('navOther');
  String get navLogs => _string('navLogs');
  String get navSettings => _string('navSettings');
  String get navAbout => _string('navAbout');

  String get pageDashboardTitle => _string('pageDashboardTitle');
  String get pageUpdaterTitle => _string('pageUpdaterTitle');
  String get pageCleanerTitle => _string('pageCleanerTitle');
  String get pageOtherTitle => _string('pageOtherTitle');
  String get pageLogsTitle => _string('pageLogsTitle');
  String get pageSettingsTitle => _string('pageSettingsTitle');
  String get pageAboutTitle => _string('pageAboutTitle');

  String get settingsAppearanceTitle => _string('settingsAppearanceTitle');
  String get settingsLanguage => _string('settingsLanguage');
  String get settingsToolVisibilityTitle =>
      _string('settingsToolVisibilityTitle');
  String get settingsShowHighRisk => _string('settingsShowHighRisk');
  String get settingsRequireAdmin => _string('settingsRequireAdmin');
  String get settingsLogsTitle => _string('settingsLogsTitle');
  String get settingsLogRetention => _string('settingsLogRetention');
  String get settingsOpenTools => _string('settingsOpenTools');
  String get settingsOpenBackups => _string('settingsOpenBackups');
  String get settingsOpenLogs => _string('settingsOpenLogs');
  String get settingsAppDataRoot => _string('settingsAppDataRoot');

  String get adminBannerTitle => _string('adminBannerTitle');
  String get adminBannerMessage => _string('adminBannerMessage');
  String get adminBannerAction => _string('adminBannerAction');
  String get adminBannerDismissedTitle =>
      _string('adminBannerDismissedTitle');
  String get adminBannerDismissedMessage =>
      _string('adminBannerDismissedMessage');
  String get adminCheckFailedTitle => _string('adminCheckFailedTitle');
  String get retryLabel => _string('retry');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return kSupportedLanguages
        .map((lang) => lang.code)
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
